# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181e5c9cd0eb1760b27bda0ee3801279dc6270e774cc415770b6487b2af3863a47f8dd0c350526a573393196f3666a81d53be76d7e9ba2259554f0da738593f4

test:
  secret_key_base: 50e7a5e6add004dc0a6dc860946efc4786b5501ffcec73f1211cd16adb665ba1cbf9523c6660efaa20a1b2d803e2154cb5f3f2e811d30d57015d5b4ebf946ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
